apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: aura
  name: status
  namespace: aura
spec:
  image: ghcr.io/nais/status:latest
  ingresses:
    - https://status.{{ cluster }}.nais.io
  readiness:
    path: /
  liveness:
    path: /
  port: 8080
  replicas:
    max: 1
    min: 1
