name: Build and deploy
on: push

env:
  docker_image: ghcr.io/nais/status:${{ github.sha }}

jobs:
  build:
    name: Build Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build and publish Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker image build --tag ${docker_image} .
          echo ${GITHUB_TOKEN} | docker login ghcr.io --username ${GITHUB_REPOSITORY} --password-stdin
          docker image push ${docker_image}
  deploy:
    name: Deploy to NAIS prod clusters
    needs: build
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        cluster: ["prod-gcp", "prod-fss", "prod-sbs"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: deploy to ${{ matrix.cluster }}
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: ${{ matrix.cluster }}
          RESOURCE: nais.yaml
          VAR: image=${{ env.docker_image }},cluster=${{ matrix.cluster }}
